### ISSUE TITLE
Method not found: 'Void VkNet.Model.RequestParams.MessagesSendParams.set_RandomId(Int64)

### ISSUE THREAD

**Issue by Fatalist23** [truecooler/VkBotFramework#1]
После первого же сообщения дропает Exeption, после него работать отказывается,
```
System.MissingMethodException: Method not found: 'Void VkNet.Model.RequestParams.MessagesSendParams.set_RandomId(Int64)'.
   at VkBotFramework.VkBot.SearchTemplatesMatchingMessageAndHandle(Message message)
   at VkBotFramework.VkBot.ProcessLongPollEvents(BotsLongPollHistoryResponse pollResponse)
   at VkBotFramework.VkBot.StartAsync()
   at VkBotFramework.VkBot.Start()
```

**Comment by idenchik1** [comment]
Вы нашли как решить эту проблему?
